# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(748, 531)
        self.mainLayout = QtWidgets.QVBoxLayout(Form)

        self.headerLayout = QtWidgets.QHBoxLayout()
        self.label = QtWidgets.QLabel(Form)
        self.headerLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.headerLayout.addWidget(self.pushButton)

        self.mainLayout.addLayout(self.headerLayout)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.horizontalLayout_4.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tableView = QtWidgets.QTableView(parent=Form)
        self.verticalLayout_2.addWidget(self.tableView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        spacerItem2 = QtWidgets.QSpacerItem(20, 408, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.groupBox)
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.groupBox)
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.mainLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Выберите строки для редактирования:"))
        self.pushButton.setText(_translate("Form", "Создать"))
        self.pushButton_3.setText(_translate("Form", "Изменить"))
        self.pushButton_2.setText(_translate("Form", "Удалить"))
        self.label_2.setText(_translate("Form", "Выбрано 0 из 0"))
        self.groupBox.setTitle(_translate("Form", "Сортировка"))
        self.pushButton_4.setText(_translate("Form", "Сбросить"))
        self.pushButton_5.setText(_translate("Form", "Применить"))
